
# A virtual machine is required to run wine
sudo: enabled

# A recent version of Ubuntu and Wine is required
dist: trusty

# Get wine and mingw cross compiler
# http://ubuntuhandbook.org/index.php/2017/01/install-wine-2-0-ubuntu-16-04-14-04-16-10/
# https://launchpad.net/~wine/+archive/ubuntu/wine-builds?field.series_filter=trusty
# https://dl.winehq.org/wine-builds/ubuntu/
before_install:
  - sudo dpkg --add-architecture i386
  - wget https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-add-repository 'https://dl.winehq.org/wine-builds/ubuntu/'
  - sudo apt-get -qq update
  - sudo apt-get install -y wine-staging
  - export PATH=/opt/wine-staging/bin:$PATH
  - wine --version
  - sudo apt-get install -y gcc-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-x86-64
  - cd examples/demo_dll/
  - make
  - cd ../../

# Repository language
language: python

# Python version
python:
  - "3.5"
  - "3.6"

# command to install dependencies
#install: "pip install -r requirements.txt"

# command to run tests
script: pytest

# Notify developers
notifications:
  email:
    recipients:
      - ernst@pleiszenburg.de
    on_success: always
    on_failure: always
